// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quiz_app.Data;

#nullable disable

namespace quiz_app.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20240723070353_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quiz_app.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "Paris"
                        },
                        new
                        {
                            AnswerId = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "London"
                        },
                        new
                        {
                            AnswerId = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Berlin"
                        },
                        new
                        {
                            AnswerId = 4,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Jupiter"
                        },
                        new
                        {
                            AnswerId = 5,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Saturn"
                        },
                        new
                        {
                            AnswerId = 6,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Mars"
                        },
                        new
                        {
                            AnswerId = 7,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Harper Lee"
                        },
                        new
                        {
                            AnswerId = 8,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Jane Austen"
                        },
                        new
                        {
                            AnswerId = 9,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Mark Twain"
                        },
                        new
                        {
                            AnswerId = 10,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "Vatican City"
                        },
                        new
                        {
                            AnswerId = 11,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Monaco"
                        },
                        new
                        {
                            AnswerId = 12,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "San Marino"
                        },
                        new
                        {
                            AnswerId = 13,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "H2O"
                        },
                        new
                        {
                            AnswerId = 14,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "O2"
                        },
                        new
                        {
                            AnswerId = 15,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "CO2"
                        },
                        new
                        {
                            AnswerId = 16,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "1912"
                        },
                        new
                        {
                            AnswerId = 17,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "1905"
                        },
                        new
                        {
                            AnswerId = 18,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "1898"
                        },
                        new
                        {
                            AnswerId = 19,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "Diamond"
                        },
                        new
                        {
                            AnswerId = 20,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Gold"
                        },
                        new
                        {
                            AnswerId = 21,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Iron"
                        },
                        new
                        {
                            AnswerId = 22,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Nile"
                        },
                        new
                        {
                            AnswerId = 23,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Amazon"
                        },
                        new
                        {
                            AnswerId = 24,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Yangtze"
                        },
                        new
                        {
                            AnswerId = 25,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "Leonardo da Vinci"
                        },
                        new
                        {
                            AnswerId = 26,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Vincent van Gogh"
                        },
                        new
                        {
                            AnswerId = 27,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Pablo Picasso"
                        },
                        new
                        {
                            AnswerId = 28,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "Mount Everest"
                        },
                        new
                        {
                            AnswerId = 29,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "K2"
                        },
                        new
                        {
                            AnswerId = 30,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Kangchenjunga"
                        },
                        new
                        {
                            AnswerId = 31,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "Alexander Fleming"
                        },
                        new
                        {
                            AnswerId = 32,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Louis Pasteur"
                        },
                        new
                        {
                            AnswerId = 33,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Marie Curie"
                        },
                        new
                        {
                            AnswerId = 34,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = "Tokyo"
                        },
                        new
                        {
                            AnswerId = 35,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Osaka"
                        },
                        new
                        {
                            AnswerId = 36,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Kyoto"
                        },
                        new
                        {
                            AnswerId = 37,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "Avocado"
                        },
                        new
                        {
                            AnswerId = 38,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Tomato"
                        },
                        new
                        {
                            AnswerId = 39,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Pepper"
                        },
                        new
                        {
                            AnswerId = 40,
                            IsCorrect = true,
                            QuestionId = 14,
                            Text = "8"
                        },
                        new
                        {
                            AnswerId = 41,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "6"
                        },
                        new
                        {
                            AnswerId = 42,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "10"
                        },
                        new
                        {
                            AnswerId = 43,
                            IsCorrect = true,
                            QuestionId = 15,
                            Text = "J.K. Rowling"
                        },
                        new
                        {
                            AnswerId = 44,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "J.R.R. Tolkien"
                        },
                        new
                        {
                            AnswerId = 45,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "George R.R. Martin"
                        },
                        new
                        {
                            AnswerId = 46,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "Ottawa"
                        },
                        new
                        {
                            AnswerId = 47,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Toronto"
                        },
                        new
                        {
                            AnswerId = 48,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Vancouver"
                        },
                        new
                        {
                            AnswerId = 49,
                            IsCorrect = true,
                            QuestionId = 17,
                            Text = "Pacific Ocean"
                        },
                        new
                        {
                            AnswerId = 50,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Atlantic Ocean"
                        },
                        new
                        {
                            AnswerId = 51,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Indian Ocean"
                        },
                        new
                        {
                            AnswerId = 52,
                            IsCorrect = true,
                            QuestionId = 18,
                            Text = "0°C"
                        },
                        new
                        {
                            AnswerId = 53,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "32°C"
                        },
                        new
                        {
                            AnswerId = 54,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "-1°C"
                        },
                        new
                        {
                            AnswerId = 55,
                            IsCorrect = true,
                            QuestionId = 19,
                            Text = "Blue Whale"
                        },
                        new
                        {
                            AnswerId = 56,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Elephant"
                        },
                        new
                        {
                            AnswerId = 57,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Giraffe"
                        },
                        new
                        {
                            AnswerId = 58,
                            IsCorrect = true,
                            QuestionId = 20,
                            Text = "Canberra"
                        },
                        new
                        {
                            AnswerId = 59,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Sydney"
                        },
                        new
                        {
                            AnswerId = 60,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Melbourne"
                        });
                });

            modelBuilder.Entity("quiz_app.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int?>("QuizAttemptId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizAttemptId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Text = "What is the capital of France?"
                        },
                        new
                        {
                            QuestionId = 2,
                            Text = "What is the largest planet in our solar system?"
                        },
                        new
                        {
                            QuestionId = 3,
                            Text = "Who wrote 'To Kill a Mockingbird'?"
                        },
                        new
                        {
                            QuestionId = 4,
                            Text = "What is the smallest country in the world?"
                        },
                        new
                        {
                            QuestionId = 5,
                            Text = "What is the chemical symbol for water?"
                        },
                        new
                        {
                            QuestionId = 6,
                            Text = "What year did the Titanic sink?"
                        },
                        new
                        {
                            QuestionId = 7,
                            Text = "What is the hardest natural substance on Earth?"
                        },
                        new
                        {
                            QuestionId = 8,
                            Text = "What is the longest river in the world?"
                        },
                        new
                        {
                            QuestionId = 9,
                            Text = "Who painted the Mona Lisa?"
                        },
                        new
                        {
                            QuestionId = 10,
                            Text = "What is the tallest mountain in the world?"
                        },
                        new
                        {
                            QuestionId = 11,
                            Text = "Who discovered penicillin?"
                        },
                        new
                        {
                            QuestionId = 12,
                            Text = "What is the capital of Japan?"
                        },
                        new
                        {
                            QuestionId = 13,
                            Text = "What is the main ingredient in guacamole?"
                        },
                        new
                        {
                            QuestionId = 14,
                            Text = "What is the square root of 64?"
                        },
                        new
                        {
                            QuestionId = 15,
                            Text = "Who is the author of 'Harry Potter' series?"
                        },
                        new
                        {
                            QuestionId = 16,
                            Text = "What is the capital of Canada?"
                        },
                        new
                        {
                            QuestionId = 17,
                            Text = "What is the largest ocean on Earth?"
                        },
                        new
                        {
                            QuestionId = 18,
                            Text = "What is the freezing point of water?"
                        },
                        new
                        {
                            QuestionId = 19,
                            Text = "What is the largest mammal in the world?"
                        },
                        new
                        {
                            QuestionId = 20,
                            Text = "What is the capital of Australia?"
                        });
                });

            modelBuilder.Entity("quiz_app.Models.QuizAttempt", b =>
                {
                    b.Property<int>("QuizAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptId"));

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptId");

                    b.ToTable("QuizAttempts");

                    b.HasData(
                        new
                        {
                            QuizAttemptId = 1,
                            AttemptDate = new DateTime(2024, 7, 23, 17, 3, 52, 640, DateTimeKind.Local).AddTicks(8089),
                            Score = 2
                        });
                });

            modelBuilder.Entity("quiz_app.Models.Answer", b =>
                {
                    b.HasOne("quiz_app.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("quiz_app.Models.Question", b =>
                {
                    b.HasOne("quiz_app.Models.QuizAttempt", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuizAttemptId");
                });

            modelBuilder.Entity("quiz_app.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("quiz_app.Models.QuizAttempt", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
